language: go
go:
   - "1.10"

before_install:
   - go get -t -v ./...
   - go get golang.org/x/tools/cmd/cover
   - go get github.com/mattn/goveralls

script:
   - go test -race -coverprofile=coverage.txt -covermode=atomic
   - go test -v -covermode=count -coverprofile=coverage.out $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

after_success:
   - bash <(curl -s https://codecov.io/bash)